// APK post-build: the app shell — one script, on every page of the app.
//
// What it owns:
//   * the hardware BACK button, and the in-page Back arrows that share it
//   * the on-screen keyboard flag the bottom bar hides behind
//
// Why one script: the back button used to be decided in three places at once
// (MainActivity.java, the shared <head> in Head.tsx, and the bottom bar's own
// injector), each with its own idea of what a press meant. The native one ran
// first and walked the WebView's history — sometimes onto the login page,
// which looked exactly like being signed out. Now the native side forwards
// the press, and IA_APP.back() below is the only decision.
//
// IMPORTANT: this script ONLY mutates files inside dist/. It never touches
// src/ or the website build (`npm run build` does not call it).

const fs = require('fs');
const path = require('path');
const { insertBeforeHeadEnd, scriptRanges } = require('./lib/html-inject.cjs');

const projectRoot = path.join(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');
const jsDir = path.join(distDir, 'kidba_assets', 'js');
const apkDir = path.join(distDir, 'apk');

const SHELL_JS = `/* APK shell: back button + keyboard. Auto-generated by scripts/apk-shell.cjs */
(function(){
  if (window.IA_APP) return;

  function plugin(name){
    try { return window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins[name] || null; } catch(e){ return null; }
  }

  // ---- Where things are ---------------------------------------------------
  var ROLE_HOME = {
    super_admin: 'super-admin-dashboard.html',
    school_admin: 'admin-dashboard.html',
    teacher: 'teacher-dashboard.html',
    student: 'student-activities.html',
    individual: 'student-activities.html',
    family: 'family.html'
  };
  var DASHBOARDS = ['student-activities', 'teacher-dashboard', 'admin-dashboard', 'super-admin-dashboard', 'family'];

  // The signed-in role's dashboard, from the cache the login page writes.
  function roleHome(){
    try {
      var raw = localStorage.getItem('auth_user') || sessionStorage.getItem('auth_user');
      var u = raw ? JSON.parse(raw) : null;
      return (u && ROLE_HOME[u.role]) || '';
    } catch(e){ return ''; }
  }
  // 'auth', 'activity', 'qibla', 'index' ...
  function page(){
    var p = (location.pathname || '').toLowerCase();
    var m = p.match(/([a-z0-9_-]+)\\.html$/);
    if (m) return m[1];
    if (p === '/' || p === '') return 'index';
    return p.replace(/^\\/+/, '').replace(/\\/+$/, '');
  }
  // Sub-pages under /apk/ link to the rest of the app with '../'.
  function base(){ return (location.pathname || '').indexOf('/apk/') !== -1 ? '../' : ''; }
  function go(file){ window.location.href = base() + file; }

  // ---- Layers ---------------------------------------------------------------
  function shown(el){
    if (!el) return false;
    var cs = window.getComputedStyle(el);
    return cs.display !== 'none' && cs.visibility !== 'hidden';
  }
  function clickFirst(root, selectors){
    for (var i = 0; i < selectors.length; i++) {
      var b = root.querySelector(selectors[i]);
      if (b && shown(b)) { b.click(); return true; }
    }
    return false;
  }

  // Close whatever is on top of the page. True if something was closed —
  // that press is spent, the page stays. Order matters: the newest layer is
  // the one the person expects to close.
  function closeTopLayer(){
    // The bottom bar's quick-access sheet.
    if (window.IA_BAR && window.IA_BAR.isSheetOpen && window.IA_BAR.isSheetOpen()) { window.IA_BAR.closeSheet(); return true; }
    // The Qibla camera.
    if (document.body.classList.contains('qibla-ar-open')) {
      var arClose = document.getElementById('qiblaArClose');
      if (arClose) { arClose.click(); return true; }
    }
    // The teacher's book reader.
    var reader = document.getElementById('bookReaderOverlay');
    if (reader && reader.classList.contains('active') && typeof window.closeBookReader === 'function') { window.closeBookReader(); return true; }
    // Native dialogs.
    var dlg = document.querySelector('dialog[open]');
    if (dlg) { try { dlg.close(); return true; } catch(e){} }
    // Bootstrap modals.
    var bsModal = document.querySelector('.modal.show');
    if (bsModal && shown(bsModal)) {
      try {
        var inst = window.bootstrap && window.bootstrap.Modal && window.bootstrap.Modal.getInstance(bsModal);
        if (inst) { inst.hide(); return true; }
      } catch(e){}
      if (clickFirst(bsModal, ['.btn-close', '[data-bs-dismiss="modal"]', '[data-dismiss="modal"]'])) return true;
    }
    // The dashboards' own modals: shown by dropping .d-none, closed by a
    // button inside, or by putting it back.
    var overlays = document.querySelectorAll('.modal-overlay:not(.d-none), .custom-modal-overlay');
    for (var i = overlays.length - 1; i >= 0; i--) {
      var ov = overlays[i];
      if (!shown(ov)) continue;
      if (clickFirst(ov, ['[data-modal-close]', '.modal-close', '.close-btn', '.btn-close', 'button[aria-label="Close"]', '.close'])) return true;
      if (ov.classList.contains('modal-overlay')) { ov.classList.add('d-none'); return true; }
      ov.remove(); return true;
    }
    // Off-canvas menus: tapping their scrim is how they close.
    var scrims = ['#adminOverlay.active', '#sidebarOverlay.active', '.sidebar-overlay.active', '.mobile-overlay.active'];
    for (var s = 0; s < scrims.length; s++) {
      var scrim = document.querySelector(scrims[s]);
      if (scrim && shown(scrim)) { scrim.click(); return true; }
    }
    return false;
  }

  // ---- The page's own rule ----------------------------------------------------
  // Pages set window.__iaBackIntercept (close a book, leave a section) and
  // the handler in src/lib/backButton.ts calls it first. This accessor keeps
  // that contract while putting the generic layers — sheet, modal, drawer —
  // in front of it: a page's rule runs only once nothing is open above it.
  var pageIntercept = null;
  function intercept(){
    if (closeTopLayer()) return true;
    try { return typeof pageIntercept === 'function' && pageIntercept() === true; } catch(e){ return false; }
  }
  try {
    Object.defineProperty(window, '__iaBackIntercept', {
      configurable: true,
      get: function(){ return intercept; },
      set: function(fn){ pageIntercept = fn; }
    });
  } catch(e){}

  // ---- Leaving ----------------------------------------------------------------
  var toastEl = null;
  function toast(msg){
    try {
      if (!toastEl) {
        toastEl = document.createElement('div');
        toastEl.style.cssText = 'position:fixed;left:50%;bottom:96px;transform:translateX(-50%);background:rgba(0,0,0,0.82);color:#fff;font:600 13px/1.3 Nunito,system-ui,sans-serif;padding:10px 18px;border-radius:22px;z-index:2147483646;pointer-events:none;box-shadow:0 8px 22px rgba(0,0,0,0.35);transition:opacity .25s;white-space:nowrap';
        document.body.appendChild(toastEl);
      }
      toastEl.textContent = msg;
      toastEl.style.opacity = '1';
      clearTimeout(toastEl.__t);
      toastEl.__t = setTimeout(function(){ if (toastEl) toastEl.style.opacity = '0'; }, 1800);
    } catch(e){}
  }
  function leave(){
    var App = plugin('App');
    if (!App) return;
    // Minimise, not exit: the session and the page come straight back when
    // the app is reopened, the way every other app on the phone behaves.
    try { if (App.minimizeApp) { App.minimizeApp(); return; } } catch(e){}
    try { App.exitApp(); } catch(e){}
  }
  var lastBackTs = 0;
  function leaveOnSecondPress(){
    var now = Date.now();
    if (now - lastBackTs < 2000) { leave(); return; }
    lastBackTs = now;
    toast('Press back again to exit');
  }

  // Was the previous page one of ours, and not the login page? Only then is
  // the WebView's history a safe place to go back to.
  function cameFromInsideApp(){
    var ref = document.referrer || '';
    if (!ref || ref.indexOf(location.origin) !== 0) return false;
    if (/\\/(auth|index)\\.html/.test(ref) || /\\/$/.test(ref.split('?')[0])) return false;
    return window.history.length > 1;
  }

  // ---- The decision ------------------------------------------------------------
  function back(){
    if (intercept()) return;
    var p = page();

    // The front door and the splash: nothing above them, so back leaves the
    // app — on the second press, like every other root screen. A single
    // press used to background the app from the login page, which read as
    // the app closing itself.
    if (p === 'auth' || p === 'index') { leaveOnSecondPress(); return; }

    // A dashboard is where a signed-in person lives. Back never walks out of
    // it into history — that is how the login page used to reappear. Two
    // presses put the app in the background.
    if (DASHBOARDS.indexOf(p) !== -1) { leaveOnSecondPress(); return; }

    // Sub-pages go to an explicit home, the same one their own Back arrow
    // points at, not to whatever the WebView remembers.
    if (p === 'activity' || p === 'club') { go('student-activities.html'); return; }
    if (p === 'teacher-reader') { go('teacher-dashboard.html'); return; }
    if (p === 'school-wall' || p === 'wall' || p === 's') { go(roleHome() || 'auth.html'); return; }

    // Qibla, Tasbeeh, FAQs, Azkar, About, the PDF viewers: back to the page
    // that opened them when that was one of ours, else to the role's home.
    if (cameFromInsideApp()) { window.history.back(); return; }
    go(roleHome() || 'auth.html');
  }

  window.IA_APP = { back: back, roleHome: roleHome, closeTopLayer: closeTopLayer, page: page };

  // ---- Hardware back --------------------------------------------------------
  // src/lib/backButton.ts owns the listener on every page built with
  // Head.tsx (and the static admin page, by substitution); it sets
  // window.__iaBackHandler before this script runs. The shell listens only
  // where that handler is absent: the bottom bar's own sub-pages and the
  // static PDF viewers.
  function attachBack(){
    if (window.__iaBackHandler) return true;
    var App = plugin('App');
    if (!App || !App.addListener) return false;
    App.addListener('backButton', function(){ back(); });
    return true;
  }
  if (!attachBack()) {
    // The bridge can land a moment after this script runs.
    var tries = 0;
    var t = setInterval(function(){
      if (attachBack() || ++tries > 40) clearInterval(t);
    }, 250);
  }

  // ---- Keyboard --------------------------------------------------------------
  // html.apk-keyboard-open while a text field has the keyboard up. The bottom
  // bar hides behind it (see apk-bottombar.css), so it never rides up above
  // the keyboard with a black gap under it.
  function setKb(open){
    try {
      document.documentElement.classList.toggle('apk-keyboard-open', !!open);
      if (document.body) document.body.classList.toggle('apk-keyboard-open', !!open);
    } catch(e){}
  }
  function isTextInput(el){
    if (!el) return false;
    var tag = (el.tagName || '').toUpperCase();
    if (tag === 'TEXTAREA') return true;
    if (tag === 'INPUT') {
      var type = (el.type || 'text').toLowerCase();
      return ['text','email','password','tel','number','search','url','date','time','datetime-local','month','week'].indexOf(type) !== -1;
    }
    return !!el.isContentEditable;
  }
  function attachKeyboard(){
    var kb = plugin('Keyboard');
    if (!kb || !kb.addListener) return false;
    kb.addListener('keyboardWillShow', function(){ setKb(true); });
    kb.addListener('keyboardWillHide', function(){ setKb(false); });
    return true;
  }
  if (!attachKeyboard()) document.addEventListener('DOMContentLoaded', function(){ if (!attachKeyboard()) setTimeout(attachKeyboard, 800); });
  // focusin fires before the keyboard is up, so the bar is gone before it
  // could be pushed; focusout waits a beat in case focus is only moving.
  document.addEventListener('focusin', function(ev){ if (isTextInput(ev.target)) setKb(true); }, true);
  document.addEventListener('focusout', function(){
    setTimeout(function(){ if (!isTextInput(document.activeElement)) setKb(false); }, 150);
  }, true);
})();
`;

// The document's own <body>, not one inside a script string: the admin page
// writes a whole printable document from a JavaScript literal.
function bodyOpenIndex(html) {
  const ranges = scriptRanges(html);
  const re = /<body[^>]*>/gi;
  let m;
  while ((m = re.exec(html)) !== null) {
    const inside = ranges.some((r) => m.index > r[0] && m.index < r[1]);
    if (!inside) return m.index + m[0].length;
  }
  return -1;
}

function inject(htmlPath, src) {
  let html = fs.readFileSync(htmlPath, 'utf8');
  if (html.indexOf('apk-shell.js') !== -1) return false;
  // Right after <body> opens — the back handler and keyboard flag should
  // exist before any of the page's own scripts run, and before a person can
  // press anything.
  const tag = `
<script src="${src}"></script>
`;
  const at = bodyOpenIndex(html);
  if (at !== -1) {
    html = html.slice(0, at) + tag + html.slice(at);
  } else {
    html = insertBeforeHeadEnd(html, tag);
  }
  fs.writeFileSync(htmlPath, html, 'utf8');
  return true;
}

function run() {
  if (!fs.existsSync(distDir)) {
    console.error('[apk-shell] dist/ not found. Run vite build first.');
    process.exit(1);
  }
  fs.mkdirSync(jsDir, { recursive: true });
  fs.writeFileSync(path.join(jsDir, 'apk-shell.js'), SHELL_JS, 'utf8');

  let injected = 0;
  for (const f of fs.readdirSync(distDir)) {
    if (!f.endsWith('.html')) continue;
    if (inject(path.join(distDir, f), 'kidba_assets/js/apk-shell.js')) injected++;
  }
  if (fs.existsSync(apkDir)) {
    for (const f of fs.readdirSync(apkDir)) {
      if (!f.endsWith('.html')) continue;
      // The sub-pages built by apk-bottombar.cjs already carry the tag.
      if (inject(path.join(apkDir, f), '../kidba_assets/js/apk-shell.js')) injected++;
    }
  }
  console.log('[apk-shell] shell written, ' + injected + ' pages injected');
}

run();
